### ISSUE TITLE
How can I update to piwik 2.10.0 ?

### ISSUE THREAD

**Issue by changwuf31** [bprodoehl/docker-piwik#1]
As said on title. How can I update to piwik latest version, using this docker container ?

Thanks

**Comment by bprodoehl** [comment]
I bumped the Piwik and nginx versions.  As soon as the Docker Hub gets it built, you should be good to go (https://registry.hub.docker.com/u/bprodoehl/piwik/build_id/25787/code/bne4ew3uxtq5i7twjftsvpu/).
