### ISSUE TITLE
Maxmind Geoip City Filename

### ISSUE THREAD

**Issue by katywings** [bprodoehl/docker-piwik#7]
Its really cool that you even download the city database in the Dockerfile. But for me it wasn't get used, i needed to change its name to: GeoIPCity.dat

(Source: http://piwik.org/faq/how-to/faq_163/) **You can find a hint at the end of this link**

**Comment by bprodoehl** [comment]
Thanks for the feedback. There's a pull request for this already. I just
need to find the time to test it out.

On Saturday, November 28, 2015, Katja Lutz notifications@github.com wrote:

> Its really cool that you even download the city database in the
> Dockerfile. But for me it wasn't get used, i needed to change its name to:
> GeoIPCity.dat
> 
> (Source: http://piwik.org/faq/how-to/faq_163/) _You can find a hint at
> the end of this link_
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bprodoehl/docker-piwik/issues/7.

## 

## 

http://www.connectify.me/

This email message is for the sole use of the intended recipient(s) and may 
contain Connectify confidential or privileged information. Any unauthorized 
review, use, disclosure or distribution is prohibited. If you are not an 
intended recipient, please contact the sender by reply email and destroy 
all copies of the original message.

**Comment by katywings** [comment]
Oh well :), indeed i need to plan my time resources too for my thousand 
tasks xD

Am 28.11.15 um 14:58 schrieb Brian Prodoehl:
